image:
  repository: ghcr.io/sapcc/redfish-exporter
  tag: "main"
  pullPolicy: IfNotPresent

service:
  port: 9220

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
users:
  # redfish users
  redfish_bb_username: DEFINED-IN-REGION-SECRETS
  redfish_bb_password: DEFINED-IN-REGION-SECRETS
  redfish_cp_username: DEFINED-IN-REGION-SECRETS
  redfish_cp_password: DEFINED-IN-REGION-SECRETS
  redfish_fw_username: DEFINED-IN-REGION-SECRETS
  redfish_fw_password: DEFINED-IN-REGION-SECRETS
  redfish_perf_username: DEFINED-IN-REGION-SECRETS
  redfish_perf_password: DEFINED-IN-REGION-SECRETS

serviceAccount:
  create: true


probes:
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 2
    failureThreshold: 3
  liveness:
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3

serviceMonitorLabels: {}
pluginPreset: true
global:
  commonLabels: {}

prometheusRules:
  create: true
  ruleGroups:
    exporterHealth: true
  disabled: {}
  ruleSelectors: []
  labels: {}
  annotations: {}
  additionalRuleLabels: {}
  additionalRuleAnnotations: {}

persesDashboards:
  create: false
  dashboardSelectors:
    - name: perses.dev/resource
      value: '"true"'
