apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redfish-exporter.fullname" . }}
  labels:
    app: {{ include "redfish-exporter.fullname" . }}
type: Opaque
stringData:
{{- with .Values.users }}
{{- if .redfish_bb_username }}
  redfish_bb_username: {{ .redfish_bb_username | quote }}
{{- end }}
{{- if .redfish_bb_password }}
  redfish_bb_password: {{ .redfish_bb_password | quote }}
{{- end }}
{{- if .redfish_cp_username }}
  redfish_cp_username: {{ .redfish_cp_username | quote }}
{{- end }}
{{- if .redfish_cp_password }}
  redfish_cp_password: {{ .redfish_cp_password | quote }}
{{- end }}
{{- if .redfish_fw_username }}
  redfish_fw_username: {{ .redfish_fw_username | quote }}
{{- end }}
{{- if .redfish_fw_password }}
  redfish_fw_password: {{ .redfish_fw_password | quote }}
{{- end }}
{{- if .redfish_perf_username }}
  redfish_perf_username: {{ .redfish_perf_username | quote }}
{{- end }}
{{- if .redfish_perf_password }}
  redfish_perf_password: {{ .redfish_perf_password | quote }}
{{- end }}
{{- end }}
