apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redfish-exporter.serviceAccountName" . }}
  labels:
    {{- include "redfish-exporter.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken | default true }}
