apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "redfish-exporter.fullname" . }}
  labels:
    {{- include "redfish-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "redfish-exporter.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: http
      path: /health
      interval: 30s
  namespaceSelector:
    any: true
