apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redfish-exporter.serviceAccountName" . }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken | default true }}
